### ISSUE TITLE
[BUG] chat.start_time is null

### ISSUE THREAD

**Issue by teisseire117** [xenova/chat-downloader#73]
Hi,

## Basic information
- Program version: 0.0.6
- Python version: 3.8.0
- Operating system: Windows 10

## Describe the bug
ChatDownloader().get_chat(url) returns 'null' for start_time

## Command/Code used
```
from chat_downloader import ChatDownloader

url = 'https://www.youtube.com/watch?v=9oX8-4dIkpss'
chat = ChatDownloader().get_chat(url)       # create a generator
print(chat.start_time)
```
### Otherwise, if using the python module, provide the following:

1. A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example):
It's the same code as above

2. Output, traceback or other information relating to the bug:
```
{'chat': <generator object YouTubeChatDownloader._get_chat_messages at 0x0000018E349784A0>, 'title': "【Visage】最終回！もう怖い！Visage正式リリース！I'm so scared!#3【周防パトラ / ハニスト】", 'duration': 12288, 'is_live': False, 'start_time': None, 'site': <chat_downloader.sites.youtube.YouTubeChatDownloader object at 0x0000018E36F52550>, 'format': <function ChatDownloader.get_chat.<locals>.<lambda> at 0x0000018E36F5B310>}
```

## Expected behavior
Should not be null

**Comment by xenova** [comment]
Let me take a look at that 👍

**Comment by xenova** [comment]
Fixed 👍 Let me know if you have any other questions.

**Comment by teisseire117** [comment]
> Fixed 👍 Let me know if you have any other questions.

Just to make sure, I get the new version by using : `pip install chat-downloader --upgrade` right ? Because I used that and I still have the 'null' problem :/

**Comment by xenova** [comment]
> > Fixed 👍 Let me know if you have any other questions.
> 
> Just to make sure, I get the new version by using : `pip install chat-downloader --upgrade` right ? Because I used that and I still have the 'null' problem :/

I still need to publish that release - which I will do now :)

**Comment by teisseire117** [comment]
> > > Fixed 👍 Let me know if you have any other questions.
> > 
> > 
> > Just to make sure, I get the new version by using : `pip install chat-downloader --upgrade` right ? Because I used that and I still have the 'null' problem :/
> 
> I still need to publish that release - which I will do now :)

Oh alright ^-^
Thank you

**Comment by xenova** [comment]
There we go 👍 You can now upgrade to 0.0.7

**Comment by teisseire117** [comment]
> There we go 👍 You can now upgrade to 0.0.7

Works perfectly !
